CREATE TABLE course_leaderboard_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES courses(id) ON UPDATE CASCADE ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    total_score NUMERIC(8, 2) NOT NULL DEFAULT 0,
    max_score NUMERIC(8, 2) NOT NULL DEFAULT 0,
    progress_pct NUMERIC(5, 2) NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (course_id, student_id)
);

CREATE TABLE assignment_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT NOT NULL UNIQUE REFERENCES assignments(id) ON UPDATE CASCADE ON DELETE CASCADE,
    submissions_count INT NOT NULL DEFAULT 0,
    graded_count INT NOT NULL DEFAULT 0,
    avg_score NUMERIC(8, 2) NOT NULL DEFAULT 0,
    last_submission_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION refresh_course_leaderboard(p_course_id BIGINT, p_student_id BIGINT) RETURNS void AS $$
DECLARE
    v_total NUMERIC(8, 2);
    v_max NUMERIC(8, 2);
    v_progress NUMERIC(5, 2);
BEGIN
    SELECT COALESCE(SUM(g.score), 0), COALESCE(SUM(a.max_score), 0)
    INTO v_total, v_max
    FROM assignments a
    LEFT JOIN submissions s ON s.assignment_id = a.id AND s.student_id = p_student_id
    LEFT JOIN grades g ON g.submission_id = s.id
    WHERE a.course_id = p_course_id;

    IF v_max > 0 THEN
        v_progress := ROUND((v_total / v_max) * 100, 2);
    ELSE
        v_progress := 0;
    END IF;

    INSERT INTO course_leaderboard_cache (course_id, student_id, total_score, max_score, progress_pct, updated_at)
    VALUES (p_course_id, p_student_id, v_total, v_max, v_progress, now())
    ON CONFLICT (course_id, student_id)
    DO UPDATE SET total_score = EXCLUDED.total_score,
                  max_score = EXCLUDED.max_score,
                  progress_pct = EXCLUDED.progress_pct,
                  updated_at = now();
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION refresh_assignment_stats(p_assignment_id BIGINT) RETURNS void AS $$
DECLARE
    v_submissions INT;
    v_graded INT;
    v_avg NUMERIC(8, 2);
    v_last TIMESTAMPTZ;
BEGIN
    SELECT COUNT(*),
           COUNT(g.id),
           COALESCE(AVG(g.score), 0),
           MAX(s.submitted_at)
    INTO v_submissions, v_graded, v_avg, v_last
    FROM submissions s
    LEFT JOIN grades g ON g.submission_id = s.id
    WHERE s.assignment_id = p_assignment_id;

    INSERT INTO assignment_stats (assignment_id, submissions_count, graded_count, avg_score, last_submission_at, updated_at)
    VALUES (p_assignment_id, v_submissions, v_graded, v_avg, v_last, now())
    ON CONFLICT (assignment_id)
    DO UPDATE SET submissions_count = EXCLUDED.submissions_count,
                  graded_count = EXCLUDED.graded_count,
                  avg_score = EXCLUDED.avg_score,
                  last_submission_at = EXCLUDED.last_submission_at,
                  updated_at = now();
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION trg_submissions_refresh() RETURNS trigger AS $$
DECLARE
    v_course_id BIGINT;
BEGIN
    SELECT course_id INTO v_course_id FROM assignments WHERE id = COALESCE(NEW.assignment_id, OLD.assignment_id);
    PERFORM refresh_assignment_stats(COALESCE(NEW.assignment_id, OLD.assignment_id));
    IF NEW.student_id IS NOT NULL THEN
        PERFORM refresh_course_leaderboard(v_course_id, NEW.student_id);
    ELSIF OLD.student_id IS NOT NULL THEN
        PERFORM refresh_course_leaderboard(v_course_id, OLD.student_id);
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION trg_grades_refresh() RETURNS trigger AS $$
DECLARE
    v_assignment_id BIGINT;
    v_course_id BIGINT;
    v_student_id BIGINT;
BEGIN
    SELECT s.assignment_id, a.course_id, s.student_id
    INTO v_assignment_id, v_course_id, v_student_id
    FROM submissions s
    JOIN assignments a ON a.id = s.assignment_id
    WHERE s.id = COALESCE(NEW.submission_id, OLD.submission_id);

    PERFORM refresh_assignment_stats(v_assignment_id);
    PERFORM refresh_course_leaderboard(v_course_id, v_student_id);
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER submissions_refresh
AFTER INSERT OR UPDATE OR DELETE ON submissions
FOR EACH ROW EXECUTE FUNCTION trg_submissions_refresh();

CREATE TRIGGER grades_refresh
AFTER INSERT OR UPDATE OR DELETE ON grades
FOR EACH ROW EXECUTE FUNCTION trg_grades_refresh();
