CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT,
    action_ts TIMESTAMPTZ NOT NULL DEFAULT now(),
    table_name TEXT NOT NULL,
    row_pk TEXT NOT NULL,
    operation TEXT NOT NULL CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE')),
    old_data JSONB,
    new_data JSONB,
    request_id UUID,
    ip TEXT,
    user_agent TEXT
);

CREATE OR REPLACE FUNCTION audit_trigger_fn() RETURNS trigger AS $$
DECLARE
    v_user_id BIGINT;
    v_request_id UUID;
    v_ip TEXT;
    v_user_agent TEXT;
    v_row_pk TEXT;
BEGIN
    v_user_id := NULLIF(current_setting('app.current_user_id', true), '')::BIGINT;
    v_request_id := NULLIF(current_setting('app.request_id', true), '')::UUID;
    v_ip := NULLIF(current_setting('app.client_ip', true), '');
    v_user_agent := NULLIF(current_setting('app.user_agent', true), '');

    v_row_pk := COALESCE((to_jsonb(NEW)->>'id'), (to_jsonb(OLD)->>'id'), 'unknown');

    INSERT INTO audit_log (
        actor_user_id,
        table_name,
        row_pk,
        operation,
        old_data,
        new_data,
        request_id,
        ip,
        user_agent
    ) VALUES (
        v_user_id,
        TG_TABLE_NAME,
        v_row_pk,
        TG_OP,
        CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) ELSE NULL END,
        CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) ELSE NULL END,
        v_request_id,
        v_ip,
        v_user_agent
    );

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_users
AFTER INSERT OR UPDATE OR DELETE ON users
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn();

CREATE TRIGGER audit_courses
AFTER INSERT OR UPDATE OR DELETE ON courses
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn();

CREATE TRIGGER audit_assignments
AFTER INSERT OR UPDATE OR DELETE ON assignments
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn();

CREATE TRIGGER audit_submissions
AFTER INSERT OR UPDATE OR DELETE ON submissions
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn();

CREATE TRIGGER audit_grades
AFTER INSERT OR UPDATE OR DELETE ON grades
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn();

CREATE TRIGGER audit_notifications
AFTER INSERT OR UPDATE OR DELETE ON notifications
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn();

CREATE TRIGGER audit_course_enrollments
AFTER INSERT OR UPDATE OR DELETE ON course_enrollments
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn();
